version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

jobs:
  build:
    working_directory: ~/SoloCA
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
          
      - run:
          name: Install Dependencies
          command: npm ci

      - run:
          name: Install Truffle
          command: 'sudo npm install -g truffle'
      - run:
          name: Check Truffle Version
          command: truffle version
      - run:
          name: Compile Smart Contracts
          command: truffle compile

      - run:
          name: test-run
          command: npm run test
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules